[manager]
54.92.129.104  # <--- Your Manager IP

[workers]
98.88.217.134  # <--- Your WorkerA IP

[all:vars]
ansible_user=ubuntu
# This tells Ansible where your .pem key is.
# We use the WSL path to your D: drive.
ansible_ssh_private_key_file=/home/nikhil/.ssh/ubuntupass.pem

# This disables a check that sometimes causes SSH to fail
ansible_ssh_common_args='-o StrictHostKeyChecking=no'